
# Docker-compose đóng gói các service cho phần backend:
#  + RabbitMQ
#  + MongoDB
#  + Redis

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  # MongoDB
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Redis
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
  
  # websocket để sau
  # worker để sau
  

volumes:
  mongo_data: